version: 2.1

executors:
  build-executor:
    docker:
      - image: gradle:7.0.1-jdk11

jobs:
  set-env:
    executor: build-executor
    steps:
      - run:
          command: |
            pwd
            touch env_vars          
            echo 'export USER=user1' >> ./env_vars
            echo 'export NAME=AFTAB' >> ./env_vars
            cat ./env_vars >> "$BASH_ENV"
            source "$BASH_ENV"
      - run:
          command: |
            pwd
            cat ./env_vars
            echo "User is" "$USER"
            echo "Name is" "$NAME"

  use-env:
    executor: build-executor
    steps:
      - run:
          command: |
            pwd
            cat ./env_vars
            echo "User is" "$USER"
            echo "Name is" "$NAME"

  test:
    executor: build-executor
    steps:
      - checkout
      - run: gradle clean test

workflows:
  build-deploy:
    jobs:
      - set-env
      - use-env:
          requires:
            - set-env
      - test
