version: 2.1

executors:
  build-executor:
    machine:
      image: ubuntu-2004:2023.02.1
    working_directory: ~/app

jobs:
  set-env:
    executor: build-executor
    steps:
      - run:
          command: |
            export ENV=dev
            echo 'export ENVIRONMENT="$ENV"' >> "$BASH_ENV"
            echo "export NEW_ENVIRONMENT='""${NEW_ENV}'" >> "$BASH_ENV"
            cat $BASH_ENV
          environment:
            ENV: dev
            NEW_ENV: prod
      - run:
          command: |
            echo $ENVIRONMENT
            echo $NEW_ENVIRONMENT

  test:
    executor: build-executor
    steps:
      - run: |
          pwd
          echo "$USER"
          ls -R
      - checkout
      - run: gradle clean test

workflows:
  build-deploy:
    jobs:
      - set-env
      - test
