version: 2.1

executors:
  build-executor:
    docker:
      - image: gradle:7.0.1-jdk11

jobs:
  test:
    executor: build-executor
    steps:
      - checkout
      - run: gradle clean test

workflows:
  build-deploy:
    jobs:
      - test
